name: Dispatch Workflow

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: macos-13
    env:
      DEVELOPER_DIR: "/Applications/Xcode_15.0.app/Contents/Developer"
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: "NO"
      CODE_SIGNING_ALLOWED: "NO"
      DERIVED_DATA: "DerivedData"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Build for Test
        run: |
          xcodebuild clean build-for-testing \
            -project Telescopure.xcodeproj \
            -scheme Telescopure \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0" \
            -derivedDataPath ${{ env.DERIVED_DATA }} | \
            xcpretty -c && exit ${PIPESTATUS[0]}

      - name: Unit Test
        run: |
          xcodebuild test-without-building \
            -project Telescopure.xcodeproj \
            -scheme Telescopure \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0" \
            -derivedDataPath ${{ env.DERIVED_DATA }} \
            -only-testing:TelescopureTests | \
            xcpretty -c && exit ${PIPESTATUS[0]}

      - name: UI Test
        run: |
          xcodebuild test-without-building \
            -project Telescopure.xcodeproj \
            -scheme Telescopure \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0" \
            -derivedDataPath ${{ env.DERIVED_DATA }} \
            -only-testing:TelescopureUITests | \
            xcpretty -c && exit ${PIPESTATUS[0]}
